---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS cluster simple'

Resources:
#  LoadBalancerSecurityGroup:
#    Type: AWS::EC2::SecurityGroup
#    Properties:
#      GroupDescription: "Security group for Kubernetes ELB"
#      VpcId: "vpc-015ec2b095350deaf"
#      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 80
#          ToPort: 80
#          CidrIp: 0.0.0.0/0
#        - IpProtocol: icmp
#          FromPort: 3
#          ToPort: 4
#          CidrIp: 0.0.0.0/0
#      SecurityGroupEgress:
#        - IpProtocol: -1
#          FromPort: -1
#          ToPort: -1
#          CidrIp: 0.0.0.0/0
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Listeners:
        - InstancePort: '32571'
          InstanceProtocol: "TCP"
          LoadBalancerPort: '80'
          Protocol: "TCP"
      HealthCheck:
        Target: "TCP:32571"
        HealthyThreshold: '2'
        UnhealthyThreshold: '6'
        Interval: '10'
        Timeout: '5'
      Scheme: "internet-facing"
      Subnets:
        - "subnet-03ca5829869d29578"
        - "subnet-041d58b358f904a88"
      LoadBalancerName: "udacity-capstone-prd"
#      Instances:
#        - "i-04be56cc76581f826"
#        - "i-0366e4ac11d4d665f"
      SecurityGroups:
        - "sg-0f1ea165e86c935f2"
